project:
  type: website
  output-dir: docs
  pre-render: 
    - powershell -ExecutionPolicy Bypass -File scripts/generate-navigation.ps1
  resources:
    - "navigation.json"
  render:
    - "*.qmd"
    - "*.md"
    - "*/README.md"
    - "**/README.md"
    - "**/SUMMARY.md"
    - "**/*.md"
    - "20250702 Azure Naming conventions/README.md"
    - "20250704 TableStorageAccess options/README.md"
    - "20250706 CosmosDB Access options/README.md"
    - "20250709 Manage GitRepo from commandline/README.md"
    - "20250711 Use http files for easy and repeatable test/README.md"
    - "20250712 Use QUARTO doc for Github repos doc/README.md"
    - "20250713 Use http files for easy and repeatable test/README.md"
    - "Travel/Paris 2025/README.md"
    - "_ISSUES/20250709 fatal error cloning a repo with Visual Studio/README.md"
    - "20250815 DIY Battery Pack/README.md"
    - "202506 Build 2025/**/*.md"
    - "202506 Build 2025/BRK114 C# 14 Language Features and Beyond/SUMMARY.md"
    - "202506 Build 2025/BRK114 C# 14 Language Features and Beyond/README.Sonnet4.md"
    - "20250723 EventHub Access options/README.md"
    - "20250825 Github repositories limitations/README.md"
    - "20250827 what is yq overview/README.md"
    - "20250712 Use QUARTO doc for Github repos doc/*.md"
    - "README.md"

website:
  title: "Dario's Learning Journey"
  description: "Technical learning notes, conference insights, and development guides"
  site-url: "https://darioairoldi.github.io/Learn"
  repo-url: "https://github.com/darioairoldi/Learn"
  repo-actions: [edit, issue]
  
  page-navigation: true
  search: true
  reader-mode: true
  
  navbar:
    background: primary
    search: true
    title: "Learning Hub"
    left:
      - icon: house-fill
        href: index.qmd
        text: "Home"
      - text: "Events"
        menu:
          - href: "202506 Build 2025/Readme.md"
            text: "Build 2025: Conference Overview"
    right:
      - text: "Culture & Travel"
        menu:
          - href: "Travel/Paris 2025/README.md"
            text: "Paris Cultural Journey 2025"
      - icon: github
        href: "https://github.com/darioairoldi/Learn"
        aria-label: "GitHub Repository"

  sidebar:
    style: "floating"
    search: true
    collapse-level: 3
    contents:
      - href: index.qmd
        text: "Home"
        icon: house-fill
      
      - section: "Events"
        icon: calendar-event
        contents:
          - section: "Build Conference 2025"
            href: "202506 Build 2025/Readme.md"
            contents:
              - href: "202506 Build 2025/Readme.md"
                text: "Conference Overview"
      
      - section: "Azure Topics"
        icon: cloud
        contents:
          - href: "20250702 Azure Naming conventions/README.md"
            text: "Azure Naming Conventions"
          - href: "20250704 TableStorageAccess options/README.md"
            text: "Table Storage Access Options"
          - href: "20250706 CosmosDB Access options/README.md"
            text: "CosmosDB Access Options"
          - href: "20250723 EventHub Access options/README.md"
            text: "EventHub Access Options"
      
      - section: "Tools"
        icon: tools
        contents:
          - section: "Development Tools"
            href: "20250709 Manage GitRepo from commandline/README.md"
            contents:
              - href: "20250709 Manage GitRepo from commandline/README.md"
                text: "Git Command Line"
              - href: "20250711 Use http files for easy and repeatable test/README.md"
                text: "HTTP Files Testing"
              - section: "Quarto Documentation"
                href: "20250712 Use QUARTO doc for Github repos doc/README.md"
                contents:
                  - href: "20250712 Use QUARTO doc for Github repos doc/README.md"
                    text: "Using Quarto"
                  - href: "20250712 Use QUARTO doc for Github repos doc/001.001 Quarto Architecture - How quarto works.md"
                    text: "How Quarto Works"
                  - href: "20250712 Use QUARTO doc for Github repos doc/001.002 Quarto Architecture - Monolithic vs. Modular Deployment.md"
                    text: "Monolithic vs. Modular Deployment"
                  - href: "20250712 Use QUARTO doc for Github repos doc/001.01. Quarto.yml document structure.md"
                    text: "Quarto.yml document structure"
                  - href: "20250712 Use QUARTO doc for Github repos doc/003.01. Quarto specific markdown features.md"
                    text: "Quarto specific markdown features"
                  - href: "20250712 Use QUARTO doc for Github repos doc/002.01. Quarto Theming and Styling.md"
                    text: "Quarto Theming and Styling"
                  - href: "20250712 Use QUARTO doc for Github repos doc/007.01. Optimizing Quarto build and deploy.md"
                    text: "Optimizing Quarto Build and Deploy"
                  - href: "20250712 Use QUARTO doc for Github repos doc/009.00 How does sidebar works.md"
                    text: "How does sidebar works"
                  - href: "20250712 Use QUARTO doc for Github repos doc/009.01 Navigation workflow.md"
                    text: "Navigation workflow"
                  - href: "20250712 Use QUARTO doc for Github repos doc/000.001 Deploying a Quarto site to GitHub Pages.md"
                    text: "Deploying to GitHub Pages"
                  - href: "20250712 Use QUARTO doc for Github repos doc/000.002 Deploying a Quarto site to Storage Accounts.md"
                    text: "Deploying to Azure Storage"
              - href: "20250713 Use http files for easy and repeatable test/README.md"
                text: "HTTP Files (Extended)"
          - section: "Data Processing"
            contents:
              - href: "20250827 what is yq overview/README.md"
                text: "yq YAML Processor Overview"
      
      - section: "Issues & Solutions"
        icon: wrench-adjustable
        contents:
          - section: "Development Issues"
            href: "_ISSUES/20250709 fatal error cloning a repo with Visual Studio/README.md"
            contents:
              - href: "_ISSUES/20250709 fatal error cloning a repo with Visual Studio/README.md"
                text: "VS Clone Error Fix (solved)"
          - section: "GitHub Repositories"
            contents:
              - href: "20250825 Github repositories limitations/README.md"
                text: "GitHub Repository Limitations"
      
      - text: "---"
      
      - section: "Other Technologies"
        icon: lightning-charge
        contents:
          - text: "DIY Li-Ion Battery Packs"
            href: "20250815 DIY Battery Pack/README.md"
      
      - text: "---"
      
      - section: "Culture & Travel"
        icon: geo-alt
        contents:
          - text: "Paris Cultural Journey 2025"
            href: "Travel/Paris 2025/README.md"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    css: styles.css
    include-after-body: 
      - _includes/right-nav.html
    grid:
      sidebar-width: 300px
      body-width: 900px  
      margin-width: 280px